export enum GROUP_ID {
  tagMarkers = "tagMarkers",
  priorityMarkers = "priorityMarkers",
  smileyMarkers = "smileyMarkers",
  taskMarkers = "taskMarkers",
  flagMarkers = "flagMarkers",
  starMarkers = "starMarkers",
  peopleMarkers = "peopleMarkers",
  arrowMarkers = "arrowMarkers",
  academicMarkers = "academicMarkers",
  socialMarkers = "socialMarkers",
  celebrationMarkers = "celebrationMarkers",
  symbolMarkers = "symbolMarkers",
  monthMarkers = "monthMarkers",
  weekMarkers = "weekMarkers",
  halfStarMarkers = "halfStarMarkers",
  otherMarkers = "otherMarkers",
}

export const GROUP_ORDER = [
  GROUP_ID.tagMarkers,
  GROUP_ID.priorityMarkers,
  GROUP_ID.taskMarkers,
  GROUP_ID.flagMarkers,
  GROUP_ID.starMarkers,
  GROUP_ID.peopleMarkers,
  GROUP_ID.symbolMarkers,
  GROUP_ID.smileyMarkers,
  GROUP_ID.arrowMarkers,
  GROUP_ID.academicMarkers,
  GROUP_ID.socialMarkers,
  GROUP_ID.celebrationMarkers,
  GROUP_ID.monthMarkers,
  GROUP_ID.weekMarkers,
  GROUP_ID.halfStarMarkers,
  GROUP_ID.otherMarkers,
];
