export const markers = {
  tagMarkers: {
    id: "tagMarkers",
    markers: [
      {
        markerId: "tag-red",
        groupId: "tagMarkers",
        resource: "markers/tagMarkers/tag-red.svg",
        hidden: false,
      },
      {
        markerId: "tag-orange",
        groupId: "tagMarkers",
        resource: "markers/tagMarkers/tag-orange.svg",
        hidden: false,
      },
      {
        markerId: "tag-yellow",
        groupId: "tagMarkers",
        resource: "markers/tagMarkers/tag-yellow.svg",
        hidden: false,
      },
      {
        markerId: "tag-green",
        groupId: "tagMarkers",
        resource: "markers/tagMarkers/tag-green.svg",
        hidden: false,
      },
      {
        markerId: "tag-blue",
        groupId: "tagMarkers",
        resource: "markers/tagMarkers/tag-blue.svg",
        hidden: false,
      },
      {
        markerId: "tag-dark-purple",
        groupId: "tagMarkers",
        resource: "markers/tagMarkers/tag-dark-purple.svg",
        hidden: false,
      },
      {
        markerId: "tag-grey",
        groupId: "tagMarkers",
        resource: "markers/tagMarkers/tag-grey.svg",
        hidden: false,
      },
      {
        markerId: "tag-dark-blue",
        groupId: "tagMarkers",
        resource: "markers/tagMarkers/tag-dark-blue.svg",
        hidden: true,
      },
    ],
    hidden: false,
  },
  priorityMarkers: {
    id: "priorityMarkers",
    markers: [
      {
        markerId: "priority-1",
        groupId: "priorityMarkers",
        resource: "markers/priorityMarkers/priority-1.svg",
        hidden: false,
      },
      {
        markerId: "priority-2",
        groupId: "priorityMarkers",
        resource: "markers/priorityMarkers/priority-2.svg",
        hidden: false,
      },
      {
        markerId: "priority-3",
        groupId: "priorityMarkers",
        resource: "markers/priorityMarkers/priority-3.svg",
        hidden: false,
      },
      {
        markerId: "priority-4",
        groupId: "priorityMarkers",
        resource: "markers/priorityMarkers/priority-4.svg",
        hidden: false,
      },
      {
        markerId: "priority-5",
        groupId: "priorityMarkers",
        resource: "markers/priorityMarkers/priority-5.svg",
        hidden: false,
      },
      {
        markerId: "priority-6",
        groupId: "priorityMarkers",
        resource: "markers/priorityMarkers/priority-6.svg",
        hidden: false,
      },
      {
        markerId: "priority-7",
        groupId: "priorityMarkers",
        resource: "markers/priorityMarkers/priority-7.svg",
        hidden: false,
      },
      {
        markerId: "priority-8",
        groupId: "priorityMarkers",
        resource: "markers/priorityMarkers/priority-8.svg",
        hidden: true,
      },
      {
        markerId: "priority-9",
        groupId: "priorityMarkers",
        resource: "markers/priorityMarkers/priority-9.svg",
        hidden: true,
      },
    ],
    hidden: false,
  },
  smileyMarkers: {
    id: "smileyMarkers",
    markers: [
      {
        markerId: "smiley-laugh",
        groupId: "smileyMarkers",
        resource: "markers/smileyMarkers/smiley-laugh.svg",
        hidden: false,
      },
      {
        markerId: "smiley-smile",
        groupId: "smileyMarkers",
        resource: "markers/smileyMarkers/smiley-smile.svg",
        hidden: false,
      },
      {
        markerId: "smiley-cry",
        groupId: "smileyMarkers",
        resource: "markers/smileyMarkers/smiley-cry.svg",
        hidden: false,
      },
      {
        markerId: "smiley-surprise",
        groupId: "smileyMarkers",
        resource: "markers/smileyMarkers/smiley-surprise.svg",
        hidden: false,
      },
      {
        markerId: "smiley-boring",
        groupId: "smileyMarkers",
        resource: "markers/smileyMarkers/smiley-boring.svg",
        hidden: false,
      },
      {
        markerId: "smiley-angry",
        groupId: "smileyMarkers",
        resource: "markers/smileyMarkers/smiley-angry.svg",
        hidden: false,
      },
      {
        markerId: "smiley-embarrass",
        groupId: "smileyMarkers",
        resource: "markers/smileyMarkers/smiley-embarrass.svg",
        hidden: false,
      },
      {
        markerId: "smiley-think",
        groupId: "smileyMarkers",
        resource: "markers/smileyMarkers/smiley-think.svg",
        hidden: false,
      },
      {
        markerId: "smiley-love",
        groupId: "smileyMarkers",
        resource: "markers/smileyMarkers/smiley-love.svg",
        hidden: false,
      },
      {
        markerId: "smiley-sad",
        groupId: "smileyMarkers",
        resource: "markers/smileyMarkers/smiley-sad.svg",
        hidden: false,
      },
      {
        markerId: "smiley-cry-laugh",
        groupId: "smileyMarkers",
        resource: "markers/smileyMarkers/smiley-cry-laugh.svg",
        hidden: false,
      },
      {
        markerId: "smiley-adore",
        groupId: "smileyMarkers",
        resource: "markers/smileyMarkers/smiley-adore.svg",
        hidden: false,
      },
      {
        markerId: "smiley-devil",
        groupId: "smileyMarkers",
        resource: "markers/smileyMarkers/smiley-devil.svg",
        hidden: false,
      },
      {
        markerId: "smiley-upset",
        groupId: "smileyMarkers",
        resource: "markers/smileyMarkers/smiley-upset.svg",
        hidden: false,
      },
    ],
    hidden: true,
  },
  taskMarkers: {
    id: "taskMarkers",
    markers: [
      {
        markerId: "task-start",
        groupId: "taskMarkers",
        resource: "markers/taskMarkers/task-start.svg",
        hidden: false,
      },
      {
        markerId: "task-oct",
        groupId: "taskMarkers",
        resource: "markers/taskMarkers/task-oct.svg",
        hidden: false,
      },
      {
        markerId: "task-quarter",
        groupId: "taskMarkers",
        resource: "markers/taskMarkers/task-quarter.svg",
        hidden: true,
      },
      {
        markerId: "task-3oct",
        groupId: "taskMarkers",
        resource: "markers/taskMarkers/task-3oct.svg",
        hidden: false,
      },
      {
        markerId: "task-half",
        groupId: "taskMarkers",
        resource: "markers/taskMarkers/task-half.svg",
        hidden: false,
      },
      {
        markerId: "task-5oct",
        groupId: "taskMarkers",
        resource: "markers/taskMarkers/task-5oct.svg",
        hidden: false,
      },
      {
        markerId: "task-3quar",
        groupId: "taskMarkers",
        resource: "markers/taskMarkers/task-3quar.svg",
        hidden: true,
      },
      {
        markerId: "task-7oct",
        groupId: "taskMarkers",
        resource: "markers/taskMarkers/task-7oct.svg",
        hidden: false,
      },
      {
        markerId: "task-done",
        groupId: "taskMarkers",
        resource: "markers/taskMarkers/task-done.svg",
        hidden: false,
      },
      {
        markerId: "task-pause",
        groupId: "taskMarkers",
        resource: "markers/taskMarkers/task-pause.png",
        hidden: true,
      },
    ],
    hidden: false,
  },
  flagMarkers: {
    id: "flagMarkers",
    markers: [
      {
        markerId: "flag-red",
        groupId: "flagMarkers",
        resource: "markers/flagMarkers/flag-red.svg",
        hidden: false,
      },
      {
        markerId: "flag-orange",
        groupId: "flagMarkers",
        resource: "markers/flagMarkers/flag-orange.svg",
        hidden: false,
      },
      {
        markerId: "flag-yellow",
        groupId: "flagMarkers",
        resource: "markers/flagMarkers/flag-yellow.svg",
        hidden: false,
      },
      {
        markerId: "flag-green",
        groupId: "flagMarkers",
        resource: "markers/flagMarkers/flag-green.svg",
        hidden: false,
      },
      {
        markerId: "flag-blue",
        groupId: "flagMarkers",
        resource: "markers/flagMarkers/flag-blue.svg",
        hidden: false,
      },
      {
        markerId: "flag-purple",
        groupId: "flagMarkers",
        resource: "markers/flagMarkers/flag-purple.svg",
        hidden: false,
      },
      {
        markerId: "flag-gray",
        groupId: "flagMarkers",
        resource: "markers/flagMarkers/flag-gray.svg",
        hidden: false,
      },
      {
        markerId: "flag-dark-blue",
        groupId: "flagMarkers",
        resource: "markers/flagMarkers/flag-dark-blue.svg",
        hidden: true,
      },
      {
        markerId: "flag-dark-green",
        groupId: "flagMarkers",
        resource: "markers/flagMarkers/flag-dark-green.svg",
        hidden: true,
      },
      {
        markerId: "flag-dark-gray",
        groupId: "flagMarkers",
        resource: "markers/flagMarkers/flag-dark-gray.svg",
        hidden: true,
      },
    ],
    hidden: false,
  },
  starMarkers: {
    id: "starMarkers",
    markers: [
      {
        markerId: "star-red",
        groupId: "starMarkers",
        resource: "markers/starMarkers/star-red.svg",
        hidden: false,
      },
      {
        markerId: "star-orange",
        groupId: "starMarkers",
        resource: "markers/starMarkers/star-orange.svg",
        hidden: false,
      },
      {
        markerId: "star-yellow",
        groupId: "starMarkers",
        resource: "markers/starMarkers/star-yellow.svg",
        hidden: false,
      },
      {
        markerId: "star-green",
        groupId: "starMarkers",
        resource: "markers/starMarkers/star-green.svg",
        hidden: false,
      },
      {
        markerId: "star-blue",
        groupId: "starMarkers",
        resource: "markers/starMarkers/star-blue.svg",
        hidden: false,
      },
      {
        markerId: "star-purple",
        groupId: "starMarkers",
        resource: "markers/starMarkers/star-purple.svg",
        hidden: false,
      },
      {
        markerId: "star-gray",
        groupId: "starMarkers",
        resource: "markers/starMarkers/star-gray.svg",
        hidden: false,
      },
      {
        markerId: "star-dark-blue",
        groupId: "starMarkers",
        resource: "markers/starMarkers/star-dark-blue.svg",
        hidden: true,
      },
      {
        markerId: "star-dark-green",
        groupId: "starMarkers",
        resource: "markers/starMarkers/star-dark-green.svg",
        hidden: true,
      },
      {
        markerId: "star-dark-gray",
        groupId: "starMarkers",
        resource: "markers/starMarkers/star-dark-gray.svg",
        hidden: true,
      },
    ],
    hidden: false,
  },
  peopleMarkers: {
    id: "peopleMarkers",
    markers: [
      {
        markerId: "people-red",
        groupId: "peopleMarkers",
        resource: "markers/peopleMarkers/people-red.svg",
        hidden: false,
      },
      {
        markerId: "people-orange",
        groupId: "peopleMarkers",
        resource: "markers/peopleMarkers/people-orange.svg",
        hidden: false,
      },
      {
        markerId: "people-yellow",
        groupId: "peopleMarkers",
        resource: "markers/peopleMarkers/people-yellow.svg",
        hidden: false,
      },
      {
        markerId: "people-green",
        groupId: "peopleMarkers",
        resource: "markers/peopleMarkers/people-green.svg",
        hidden: false,
      },
      {
        markerId: "people-blue",
        groupId: "peopleMarkers",
        resource: "markers/peopleMarkers/people-blue.svg",
        hidden: false,
      },
      {
        markerId: "people-purple",
        groupId: "peopleMarkers",
        resource: "markers/peopleMarkers/people-purple.svg",
        hidden: false,
      },
      {
        markerId: "people-gray",
        groupId: "peopleMarkers",
        resource: "markers/peopleMarkers/people-gray.svg",
        hidden: false,
      },
      {
        markerId: "people-dark-blue",
        groupId: "peopleMarkers",
        resource: "markers/peopleMarkers/people-dark-blue.svg",
        hidden: true,
      },
      {
        markerId: "people-dark-green",
        groupId: "peopleMarkers",
        resource: "markers/peopleMarkers/people-dark-green.svg",
        hidden: true,
      },
      {
        markerId: "people-dark-gray",
        groupId: "peopleMarkers",
        resource: "markers/peopleMarkers/people-dark-gray.svg",
        hidden: true,
      },
    ],
    hidden: false,
  },
  arrowMarkers: {
    id: "arrowMarkers",
    markers: [
      {
        markerId: "arrow-left",
        groupId: "arrowMarkers",
        resource: "markers/arrowMarkers/arrow-left.svg",
        hidden: false,
      },
      {
        markerId: "arrow-right",
        groupId: "arrowMarkers",
        resource: "markers/arrowMarkers/arrow-right.svg",
        hidden: false,
      },
      {
        markerId: "arrow-up",
        groupId: "arrowMarkers",
        resource: "markers/arrowMarkers/arrow-up.svg",
        hidden: false,
      },
      {
        markerId: "arrow-down",
        groupId: "arrowMarkers",
        resource: "markers/arrowMarkers/arrow-down.svg",
        hidden: false,
      },
      {
        markerId: "arrow-left-right",
        groupId: "arrowMarkers",
        resource: "markers/arrowMarkers/arrow-left-right.svg",
        hidden: false,
      },
      {
        markerId: "arrow-up-down",
        groupId: "arrowMarkers",
        resource: "markers/arrowMarkers/arrow-up-down.svg",
        hidden: false,
      },
      {
        markerId: "arrow-refresh",
        groupId: "arrowMarkers",
        resource: "markers/arrowMarkers/arrow-refresh.svg",
        hidden: false,
      },
      {
        markerId: "arrow-up-right",
        groupId: "arrowMarkers",
        resource: "markers/arrowMarkers/arrow-up-right.svg",
        hidden: true,
      },
      {
        markerId: "arrow-down-right",
        groupId: "arrowMarkers",
        resource: "markers/arrowMarkers/arrow-down-right.svg",
        hidden: true,
      },
      {
        markerId: "arrow-down-left",
        groupId: "arrowMarkers",
        resource: "markers/arrowMarkers/arrow-down-left.svg",
        hidden: true,
      },
      {
        markerId: "arrow-up-left",
        groupId: "arrowMarkers",
        resource: "markers/arrowMarkers/arrow-up-left.svg",
        hidden: true,
      },
    ],
    hidden: true,
  },
  academicMarkers: {
    id: "academicMarkers",
    markers: [
      {
        markerId: "c_symbol_quote",
        groupId: "academicMarkers",
        resource: "markers/academicMarkers/c_symbol_quote.svg",
        hidden: false,
      },
      {
        markerId: "c_symbol_apostrophe",
        groupId: "academicMarkers",
        resource: "markers/academicMarkers/c_symbol_apostrophe.svg",
        hidden: false,
      },
      {
        markerId: "symbol-question",
        groupId: "academicMarkers",
        resource: "markers/academicMarkers/symbol-question.svg",
        hidden: false,
      },
      {
        markerId: "symbol-attention",
        groupId: "academicMarkers",
        resource: "markers/academicMarkers/symbol-attention.svg",
        hidden: false,
      },
      {
        markerId: "symbol-pause",
        groupId: "academicMarkers",
        resource: "markers/academicMarkers/symbol-pause.svg",
        hidden: false,
      },
      {
        markerId: "symbol-wrong",
        groupId: "academicMarkers",
        resource: "markers/academicMarkers/symbol-wrong.svg",
        hidden: false,
      },
      {
        markerId: "symbol-about",
        groupId: "academicMarkers",
        resource: "markers/academicMarkers/symbol-about.svg",
        hidden: false,
      },
      {
        markerId: "symbol-plus",
        groupId: "academicMarkers",
        resource: "markers/academicMarkers/symbol-plus.svg",
        hidden: false,
      },
      {
        markerId: "symbol-minus",
        groupId: "academicMarkers",
        resource: "markers/academicMarkers/symbol-minus.svg",
        hidden: false,
      },
      {
        markerId: "symbol-divide",
        groupId: "academicMarkers",
        resource: "markers/academicMarkers/symbol-divide.svg",
        hidden: false,
      },
      {
        markerId: "symbol-equality",
        groupId: "academicMarkers",
        resource: "markers/academicMarkers/symbol-equality.svg",
        hidden: false,
      },
      {
        markerId: "symbol-right",
        groupId: "academicMarkers",
        resource: "markers/academicMarkers/symbol-right.svg",
        hidden: false,
      },
      {
        markerId: "symbol-code",
        groupId: "academicMarkers",
        resource: "markers/academicMarkers/symbol-code.svg",
        hidden: false,
      },
      {
        markerId: "symbol-not-equality",
        groupId: "academicMarkers",
        resource: "markers/academicMarkers/symbol-not-equality.svg",
        hidden: false,
      },
    ],
    hidden: true,
  },
  socialMarkers: {
    id: "socialMarkers",
    markers: [
      {
        markerId: "c_symbol_broken_heart",
        groupId: "socialMarkers",
        resource: "markers/socialMarkers/c_symbol_broken_heart.svg",
        hidden: false,
      },
      {
        markerId: "c_symbol_contact",
        groupId: "socialMarkers",
        resource: "markers/socialMarkers/c_symbol_contact.svg",
        hidden: false,
      },
      {
        markerId: "symbol-no-entry",
        groupId: "socialMarkers",
        resource: "markers/socialMarkers/symbol-no-entry.svg",
        hidden: false,
      },
      {
        markerId: "symbol-notice",
        groupId: "socialMarkers",
        resource: "markers/socialMarkers/symbol-notice.svg",
        hidden: false,
      },
      {
        markerId: "symbol-rss",
        groupId: "socialMarkers",
        resource: "markers/socialMarkers/symbol-rss.svg",
        hidden: false,
      },
      {
        markerId: "symbol_forward",
        groupId: "socialMarkers",
        resource: "markers/socialMarkers/symbol_forward.svg",
        hidden: false,
      },
      {
        markerId: "symbol-share",
        groupId: "socialMarkers",
        resource: "markers/socialMarkers/symbol-share.svg",
        hidden: false,
      },
      {
        markerId: "symbol-comment",
        groupId: "socialMarkers",
        resource: "markers/socialMarkers/symbol-comment.svg",
        hidden: false,
      },
    ],
    hidden: true,
  },
  celebrationMarkers: {
    id: "celebrationMarkers",
    markers: [
      {
        markerId: "celebration-ribbon",
        groupId: "celebrationMarkers",
        resource: "markers/celebrationMarkers/celebration-ribbon.svg",
        hidden: true,
      },
      {
        markerId: "celebration-clap",
        groupId: "celebrationMarkers",
        resource: "markers/celebrationMarkers/celebration-clap.svg",
        hidden: true,
      },
      {
        markerId: "celebration-100",
        groupId: "celebrationMarkers",
        resource: "markers/celebrationMarkers/celebration-100.svg",
        hidden: true,
      },
      {
        markerId: "celebration-birthday",
        groupId: "celebrationMarkers",
        resource: "markers/celebrationMarkers/celebration-birthday.svg",
        hidden: true,
      },
      {
        markerId: "celebration-king",
        groupId: "celebrationMarkers",
        resource: "markers/celebrationMarkers/celebration-king.svg",
        hidden: true,
      },
      {
        markerId: "celebration-cheers",
        groupId: "celebrationMarkers",
        resource: "markers/celebrationMarkers/celebration-cheers.svg",
        hidden: true,
      },
      {
        markerId: "celebration-boom",
        groupId: "celebrationMarkers",
        resource: "markers/celebrationMarkers/celebration-boom.svg",
        hidden: true,
      },
      {
        markerId: "celebration-kiss",
        groupId: "celebrationMarkers",
        resource: "markers/celebrationMarkers/celebration-kiss.svg",
        hidden: true,
      },
      {
        markerId: "celebration-five",
        groupId: "celebrationMarkers",
        resource: "markers/celebrationMarkers/celebration-five.svg",
        hidden: true,
      },
    ],
    hidden: true,
  },
  symbolMarkers: {
    id: "symbolMarkers",
    markers: [
      {
        markerId: "c_symbol_heart",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_symbol_heart.svg",
        hidden: false,
      },
      {
        markerId: "c_symbol_like",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_symbol_like.svg",
        hidden: false,
      },
      {
        markerId: "c_symbol_dislike",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_symbol_dislike.svg",
        hidden: false,
      },
      {
        markerId: "symbol-pin",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/symbol-pin.svg",
        hidden: false,
      },
      {
        markerId: "symbol-idea",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/symbol-idea.svg",
        hidden: false,
      },
      {
        markerId: "symbol-lightning",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/symbol-lightning.svg",
        hidden: false,
      },
      {
        markerId: "c_symbol_hourglass",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_symbol_hourglass.svg",
        hidden: false,
      },
      {
        markerId: "c_symbol_telephone",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_symbol_telephone.svg",
        hidden: false,
      },
      {
        markerId: "c_symbol_pen",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_symbol_pen.svg",
        hidden: false,
      },
      {
        markerId: "c_symbol_music",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_symbol_music.svg",
        hidden: false,
      },
      {
        markerId: "symbol-entertainment",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/symbol-entertainment.svg",
        hidden: false,
      },
      {
        markerId: "symbol-100",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/symbol-100.svg",
        hidden: false,
      },
      {
        markerId: "c_symbol_flight",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_symbol_flight.svg",
        hidden: false,
      },
      {
        markerId: "symbol-run",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/symbol-run.svg",
        hidden: false,
      },
      {
        markerId: "symbol-exclam",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/symbol-exclam.svg",
        hidden: false,
      },
      {
        markerId: "symbol-question",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/symbol-question.svg",
        hidden: false,
      },
      {
        markerId: "symbol-plus",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/symbol-plus.svg",
        hidden: true,
      },
      {
        markerId: "symbol-minus",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/symbol-minus.svg",
        hidden: true,
      },
      {
        markerId: "symbol-info",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/symbol-info.svg",
        hidden: true,
      },
      {
        markerId: "symbol-attention",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/symbol-attention.svg",
        hidden: true,
      },
      {
        markerId: "symbol-wrong",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/symbol-wrong.svg",
        hidden: true,
      },
      {
        markerId: "symbol-right",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/symbol-right.svg",
        hidden: true,
      },
      {
        markerId: "symbol-pause",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/symbol-pause.svg",
        hidden: true,
      },
      {
        markerId: "c_simbol-plus",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_simbol-plus.svg",
        hidden: true,
      },
      {
        markerId: "c_simbol-minus",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_simbol-minus.svg",
        hidden: true,
      },
      {
        markerId: "c_simbol-question",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_simbol-question.svg",
        hidden: true,
      },
      {
        markerId: "c_simbol-info",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_simbol-info.svg",
        hidden: true,
      },
      {
        markerId: "c_simbol-wrong",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_simbol-wrong.svg",
        hidden: true,
      },
      {
        markerId: "c_simbol-right",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_simbol-right.svg",
        hidden: true,
      },
      {
        markerId: "c_simbol-pause",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_simbol-pause.svg",
        hidden: true,
      },
      {
        markerId: "c_symbol_contact",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_symbol_contact.svg",
        hidden: true,
      },
      {
        markerId: "c_symbol_drink",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_symbol_drink.svg",
        hidden: true,
      },
      {
        markerId: "c_symbol_line_graph",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_symbol_line_graph.svg",
        hidden: true,
      },
      {
        markerId: "c_symbol_medals",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_symbol_medals.svg",
        hidden: true,
      },
      {
        markerId: "c_symbol_thermometer",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_symbol_thermometer.svg",
        hidden: true,
      },
      {
        markerId: "c_symbol_money",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_symbol_money.svg",
        hidden: true,
      },
      {
        markerId: "c_symbol_bar_chart",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_symbol_bar_chart.svg",
        hidden: true,
      },
      {
        markerId: "c_simbol-exclam",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_simbol-exclam.svg",
        hidden: true,
      },
      {
        markerId: "c_symbol_pie_chart",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_symbol_pie_chart.svg",
        hidden: true,
      },
      {
        markerId: "c_symbol_shopping_cart",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_symbol_shopping_cart.svg",
        hidden: true,
      },
      {
        markerId: "c_symbol_exercise",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_symbol_exercise.svg",
        hidden: true,
      },
      {
        markerId: "c_symbol_trophy",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_symbol_trophy.svg",
        hidden: true,
      },
      {
        markerId: "symbol-unlock",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/symbol-unlock.svg",
        hidden: true,
      },
      {
        markerId: "c_symbol_lock",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/c_symbol_lock.svg",
        hidden: true,
      },
      {
        markerId: "symbol-diamond",
        groupId: "symbolMarkers",
        resource: "markers/symbolMarkers/symbol-diamond.svg",
        hidden: true,
      },
    ],
    hidden: false,
  },
  monthMarkers: {
    id: "monthMarkers",
    markers: [
      {
        markerId: "month-jan",
        groupId: "monthMarkers",
        resource: "markers/monthMarkers/month-jan.svg",
        hidden: false,
      },
      {
        markerId: "month-feb",
        groupId: "monthMarkers",
        resource: "markers/monthMarkers/month-feb.svg",
        hidden: false,
      },
      {
        markerId: "month-mar",
        groupId: "monthMarkers",
        resource: "markers/monthMarkers/month-mar.svg",
        hidden: false,
      },
      {
        markerId: "month-apr",
        groupId: "monthMarkers",
        resource: "markers/monthMarkers/month-apr.svg",
        hidden: false,
      },
      {
        markerId: "month-may",
        groupId: "monthMarkers",
        resource: "markers/monthMarkers/month-may.svg",
        hidden: false,
      },
      {
        markerId: "month-jun",
        groupId: "monthMarkers",
        resource: "markers/monthMarkers/month-jun.svg",
        hidden: false,
      },
      {
        markerId: "month-jul",
        groupId: "monthMarkers",
        resource: "markers/monthMarkers/month-jul.svg",
        hidden: false,
      },
      {
        markerId: "month-aug",
        groupId: "monthMarkers",
        resource: "markers/monthMarkers/month-aug.svg",
        hidden: false,
      },
      {
        markerId: "month-sep",
        groupId: "monthMarkers",
        resource: "markers/monthMarkers/month-sep.svg",
        hidden: false,
      },
      {
        markerId: "month-oct",
        groupId: "monthMarkers",
        resource: "markers/monthMarkers/month-oct.svg",
        hidden: false,
      },
      {
        markerId: "month-nov",
        groupId: "monthMarkers",
        resource: "markers/monthMarkers/month-nov.svg",
        hidden: false,
      },
      {
        markerId: "month-dec",
        groupId: "monthMarkers",
        resource: "markers/monthMarkers/month-dec.svg",
        hidden: false,
      },
    ],
    hidden: true,
  },
  weekMarkers: {
    id: "weekMarkers",
    markers: [
      {
        markerId: "week-sun",
        groupId: "weekMarkers",
        resource: "markers/weekMarkers/week-sun.svg",
        hidden: false,
      },
      {
        markerId: "week-mon",
        groupId: "weekMarkers",
        resource: "markers/weekMarkers/week-mon.svg",
        hidden: false,
      },
      {
        markerId: "week-tue",
        groupId: "weekMarkers",
        resource: "markers/weekMarkers/week-tue.svg",
        hidden: false,
      },
      {
        markerId: "week-wed",
        groupId: "weekMarkers",
        resource: "markers/weekMarkers/week-wed.svg",
        hidden: false,
      },
      {
        markerId: "week-thu",
        groupId: "weekMarkers",
        resource: "markers/weekMarkers/week-thu.svg",
        hidden: false,
      },
      {
        markerId: "week-fri",
        groupId: "weekMarkers",
        resource: "markers/weekMarkers/week-fri.svg",
        hidden: false,
      },
      {
        markerId: "week-sat",
        groupId: "weekMarkers",
        resource: "markers/weekMarkers/week-sat.svg",
        hidden: false,
      },
    ],
    hidden: true,
  },
  halfStarMarkers: {
    id: "halfStarMarkers",
    markers: [
      {
        markerId: "half-star-green",
        groupId: "halfStarMarkers",
        resource: "markers/halfStarMarkers/half-star-green.png",
        hidden: true,
      },
      {
        markerId: "half-star-red",
        groupId: "halfStarMarkers",
        resource: "markers/halfStarMarkers/half-star-red.png",
        hidden: true,
      },
      {
        markerId: "half-star-yellow",
        groupId: "halfStarMarkers",
        resource: "markers/halfStarMarkers/half-star-yellow.png",
        hidden: true,
      },
      {
        markerId: "half-star-purple",
        groupId: "halfStarMarkers",
        resource: "markers/halfStarMarkers/half-star-purple.png",
        hidden: true,
      },
      {
        markerId: "half-star-blue",
        groupId: "halfStarMarkers",
        resource: "markers/halfStarMarkers/half-star-blue.png",
        hidden: true,
      },
      {
        markerId: "half-star-gray",
        groupId: "halfStarMarkers",
        resource: "markers/halfStarMarkers/half-star-gray.png",
        hidden: true,
      },
    ],
    hidden: true,
  },
  otherMarkers: {
    id: "otherMarkers",
    markers: [
      {
        markerId: "other-calendar",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/other-calendar.png",
        hidden: true,
      },
      {
        markerId: "other-email",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/other-email.png",
        hidden: true,
      },
      {
        markerId: "other-phone",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/other-phone.png",
        hidden: true,
      },
      {
        markerId: "other-phone2",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/other-phone2.png",
        hidden: true,
      },
      {
        markerId: "other-fax",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/other-fax.png",
        hidden: true,
      },
      {
        markerId: "other-people",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/other-people.png",
        hidden: true,
      },
      {
        markerId: "other-people2",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/other-people2.png",
        hidden: true,
      },
      {
        markerId: "other-clock",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/other-clock.png",
        hidden: true,
      },
      {
        markerId: "other-coffee-cup",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/other-coffee-cup.png",
        hidden: true,
      },
      {
        markerId: "other-question",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/other-question.svg",
        hidden: true,
      },
      {
        markerId: "other-exclam",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/other-exclam.svg",
        hidden: true,
      },
      {
        markerId: "other-lightbulb",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/other-lightbulb.png",
        hidden: true,
      },
      {
        markerId: "other-businesscard",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/other-businesscard.png",
        hidden: true,
      },
      {
        markerId: "other-social",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/other-social.png",
        hidden: true,
      },
      {
        markerId: "other-chat",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/other-chat.png",
        hidden: true,
      },
      {
        markerId: "other-note",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/other-note.png",
        hidden: true,
      },
      {
        markerId: "other-lock",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/other-lock.png",
        hidden: true,
      },
      {
        markerId: "other-unlock",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/other-unlock.png",
        hidden: true,
      },
      {
        markerId: "other-yes",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/other-yes.svg",
        hidden: true,
      },
      {
        markerId: "other-no",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/other-no.svg",
        hidden: true,
      },
      {
        markerId: "other-bomb",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/other-bomb.png",
        hidden: true,
      },
      {
        markerId: "symbol-info",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/symbol-info.svg",
        hidden: true,
      },
      {
        markerId: "c_symbol_line_graph",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/c_symbol_line_graph.svg",
        hidden: true,
      },
      {
        markerId: "c_symbol_shopping_cart",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/c_symbol_shopping_cart.svg",
        hidden: true,
      },
      {
        markerId: "c_symbol_medals",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/c_symbol_medals.svg",
        hidden: true,
      },
      {
        markerId: "c_symbol_trophy",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/c_symbol_trophy.svg",
        hidden: true,
      },
      {
        markerId: "symbol-image",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/symbol-image.svg",
        hidden: true,
      },
      {
        markerId: "c_symbol_exercise",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/c_symbol_exercise.svg",
        hidden: true,
      },
      {
        markerId: "c_simbol-plus",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/c_simbol-plus.svg",
        hidden: true,
      },
      {
        markerId: "c_simbol-minus",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/c_simbol-minus.svg",
        hidden: true,
      },
      {
        markerId: "c_simbol-question",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/c_simbol-question.svg",
        hidden: true,
      },
      {
        markerId: "c_simbol-info",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/c_simbol-info.svg",
        hidden: true,
      },
      {
        markerId: "c_simbol-wrong",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/c_simbol-wrong.svg",
        hidden: true,
      },
      {
        markerId: "c_simbol-right",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/c_simbol-right.svg",
        hidden: true,
      },
      {
        markerId: "c_simbol-pause",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/c_simbol-pause.svg",
        hidden: true,
      },
      {
        markerId: "c_symbol_thermometer",
        groupId: "otherMarkers",
        resource: "markers/otherMarkers/c_symbol_thermometer.svg",
        hidden: true,
      },
    ],
    hidden: true,
  },
};
