export const UI_STATUS = {
  LAYOUT: 'layout',
  ANIMATION: 'animation',
  PINCH: 'pinching',
  DRAG: 'drag',
  ADD_RELATIONSHIP: 'addRelationship',
  ADD_FLOATINGTOPIC: 'addFloatingTopic',
  EDIT_TITLE: 'editTitle',
  DRAG_VIEWPORT: 'dragViewport',
  LOADING_IMAGE: 'loadingImage',
  DE_FOCUS: 'deFocus',
  DRAG_TOPIC_SELECT_BOX: 'dragTopicSelectBox',
  SHOW_BRANCH_ONLY: 'showBranchOnly',
  FILTER_MODE: 'filterMode',
  MULTI_SELECT_MODE: 'multiSelectMode',
  CHANGING_THEME: 'changingTheme',
} as const;
