import { BRANCHCONNECTION } from "./styles";
export enum STRUCTURECLASS {
  LOGICRIGHT = "org.xmind.ui.logic.right",
  LOGICLEFT = "org.xmind.ui.logic.left",
  TREERIGHT = "org.xmind.ui.tree.right",
  TREELEFT = "org.xmind.ui.tree.left",
  TREESIDED = "org.xmind.ui.timeline.vertical",
  ORGCHARTDOWN = "org.xmind.ui.org-chart.down",
  ORGCHARTUP = "org.xmind.ui.org-chart.up",
  MAPCLOCKWISE = "org.xmind.ui.map.clockwise",
  MAPANTICLOCKWISE = "org.xmind.ui.map.anticlockwise",
  MAP = "org.xmind.ui.map",
  MAPUNBALANCED = "org.xmind.ui.map.unbalanced",
  MAPFLOATING = "org.xmind.ui.map.floating",
  MAPFLOATINGCLOCKWISE = "org.xmind.ui.map.floating.clockwise",
  MAPFLOATINGANTICLOCKWISE = "org.xmind.ui.map.floating.anticlockwise",
  TIMELINETHROUGHVERTICAL = "org.xmind.ui.timeline.through.vertical",
  TIMELINESIDEDHORIZONTAL = "org.xmind.ui.timeline.sided.horizontal",
  TIMELINEHORIZONTAL = "org.xmind.ui.timeline.horizontal",
  FISHBONELEFTHEADED = "org.xmind.ui.fishbone.leftHeaded",
  LEFTHEADTOPBONE = "org.xmind.ui.fishbone.structure.lefthead.topbone",
  LEFTHEADBOTTOMBONE = "org.xmind.ui.fishbone.structure.lefthead.bottombone",
  FISHBONERIGHTHEADED = "org.xmind.ui.fishbone.rightHeaded",
  RIGHTHEADTOPBONE = "org.xmind.ui.fishbone.structure.righthead.topbone",
  RIGHTHEADBOTTOMBONE = "org.xmind.ui.fishbone.structure.righthead.bottombone",
  SPREADSHEET = "org.xmind.ui.spreadsheet",
  COLUMNSPREADSHEET = "org.xmind.ui.spreadsheet.column",
  TREETABLE = "org.xmind.ui.treetable",
  TOPTITLETREETABLE = "org.xmind.ui.treetable.toptitle",
  // private
  SPREADSHEETROW = "org.xmind.ui.structure.spreadsheet.row",
  SPREADSHEETCOLUMN = "org.xmind.ui.structure.column.spreadsheet",
  FISHBONELEFTHEADTOP = "org.xmind.ui.fishbone.leftHeaded.top",
  FISHBONELEFTHEADBOTTOM = "org.xmind.ui.fishbone.leftHeaded.bottom",
  FISHBONERIGHTHEADTOP = "org.xmind.ui.fishbone.rightHeaded.top",
  FISHBONERIGHTHEADBOTTOM = "org.xmind.ui.fishbone.rightHeaded.bottom",
  TIMELINEHORIZONTALUP = "org.xmind.ui.timeline.horizontal.up",
  TIMELINEHORIZONTALDOWN = "org.xmind.ui.timeline.horizontal.down",
  // 已废弃，为了兼容旧 structure
  LOGICCHARTRIGHT = "org.xmind.ui.logic-chart.right",
  LOGICCHARTLEFT = "org.xmind.ui.logic-chart.left",
  BRACERIGHT = "org.xmind.ui.brace.right",
  BRACELEFT = "org.xmind.ui.brace.left",
  // eslint-disable-next-line @typescript-eslint/no-duplicate-enum-values
  TIMELINEVERTICAL = "org.xmind.ui.timeline.vertical",
}
export const EXPOSED_STRUCTURE = [
  STRUCTURECLASS.LOGICRIGHT,
  STRUCTURECLASS.LOGICLEFT,
  STRUCTURECLASS.TREERIGHT,
  STRUCTURECLASS.TREELEFT,
  STRUCTURECLASS.ORGCHARTDOWN,
  STRUCTURECLASS.ORGCHARTUP,
  STRUCTURECLASS.MAPCLOCKWISE,
  STRUCTURECLASS.MAPANTICLOCKWISE,
  STRUCTURECLASS.MAP,
  STRUCTURECLASS.MAPUNBALANCED,
  STRUCTURECLASS.TIMELINETHROUGHVERTICAL,
  STRUCTURECLASS.TIMELINESIDEDHORIZONTAL,
  STRUCTURECLASS.TIMELINEHORIZONTAL,
  STRUCTURECLASS.TREESIDED,
  STRUCTURECLASS.FISHBONELEFTHEADED,
  STRUCTURECLASS.FISHBONERIGHTHEADED,
  STRUCTURECLASS.SPREADSHEET,
  STRUCTURECLASS.COLUMNSPREADSHEET,
  STRUCTURECLASS.BRACELEFT,
  STRUCTURECLASS.BRACERIGHT,
  STRUCTURECLASS.TOPTITLETREETABLE,
  STRUCTURECLASS.TREETABLE,
];
export const MAP_LIKE_STRUCTURES = [
  STRUCTURECLASS.MAP,
  STRUCTURECLASS.MAPUNBALANCED,
  STRUCTURECLASS.MAPANTICLOCKWISE,
  STRUCTURECLASS.MAPCLOCKWISE,
  STRUCTURECLASS.MAPFLOATING,
  STRUCTURECLASS.MAPFLOATINGCLOCKWISE,
  STRUCTURECLASS.MAPFLOATINGANTICLOCKWISE,
];
export const LOGIC_CHART_STRUCTURES = [
  STRUCTURECLASS.LOGICLEFT,
  STRUCTURECLASS.LOGICRIGHT,
];
export const ORG_CHART_STRUCTURES = [
  STRUCTURECLASS.ORGCHARTUP,
  STRUCTURECLASS.ORGCHARTDOWN,
];
export const ATTACHED_EXPOSED_STRUCTURE = EXPOSED_STRUCTURE.filter((item) => {
  return !MAP_LIKE_STRUCTURES.includes(item);
});
export const LEFT_EXPOSED_STRUCTURE = ATTACHED_EXPOSED_STRUCTURE.filter(
  (item) => {
    return ![
      STRUCTURECLASS.LOGICRIGHT,
      STRUCTURECLASS.BRACERIGHT,
      STRUCTURECLASS.FISHBONELEFTHEADED,
      STRUCTURECLASS.TIMELINEHORIZONTAL,
      STRUCTURECLASS.TIMELINESIDEDHORIZONTAL,
    ].includes(item);
  },
);
export const RIGHT_EXPOSED_STRUCTURE = ATTACHED_EXPOSED_STRUCTURE.filter(
  (item) => {
    return ![
      STRUCTURECLASS.LOGICLEFT,
      STRUCTURECLASS.BRACELEFT,
      STRUCTURECLASS.FISHBONERIGHTHEADED,
    ].includes(item);
  },
);
export const TOP_EXPOSED_STRUCTURE = ATTACHED_EXPOSED_STRUCTURE.filter(
  (item) => {
    return ![
      STRUCTURECLASS.ORGCHARTDOWN,
      STRUCTURECLASS.TIMELINEVERTICAL,
      STRUCTURECLASS.TREELEFT,
      STRUCTURECLASS.TREERIGHT,
      STRUCTURECLASS.TIMELINETHROUGHVERTICAL,
    ].includes(item);
  },
);
export const DOWN_EXPOSED_STRUCTURE = ATTACHED_EXPOSED_STRUCTURE.filter(
  (item) => {
    return ![STRUCTURECLASS.ORGCHARTUP].includes(item);
  },
);
export const TREE_LEFT_EXPOSED_STRUCTURE = LEFT_EXPOSED_STRUCTURE.filter(
  (item) => {
    return ![STRUCTURECLASS.TIMELINEVERTICAL].includes(item);
  },
);
export const TREE_RIGHT_EXPOSED_STRUCTURE = RIGHT_EXPOSED_STRUCTURE;
export const TREE_TABLE_EXPOSED_STRUCTURE = ATTACHED_EXPOSED_STRUCTURE.filter(
  (item) => {
    return ![
      STRUCTURECLASS.SPREADSHEET,
      STRUCTURECLASS.COLUMNSPREADSHEET,
    ].includes(item);
  },
);
export const SIMILAR_STRUCTURE_MAP = {
  [STRUCTURECLASS.FISHBONELEFTHEADED]: STRUCTURECLASS.FISHBONERIGHTHEADED,
  [STRUCTURECLASS.FISHBONERIGHTHEADED]: STRUCTURECLASS.FISHBONELEFTHEADED,
  [STRUCTURECLASS.BRACELEFT]: STRUCTURECLASS.BRACERIGHT,
  [STRUCTURECLASS.BRACERIGHT]: STRUCTURECLASS.BRACELEFT,
  [STRUCTURECLASS.LOGICLEFT]: STRUCTURECLASS.LOGICRIGHT,
  [STRUCTURECLASS.LOGICRIGHT]: STRUCTURECLASS.LOGICLEFT,
  [STRUCTURECLASS.ORGCHARTDOWN]: STRUCTURECLASS.ORGCHARTUP,
  [STRUCTURECLASS.ORGCHARTUP]: STRUCTURECLASS.ORGCHARTDOWN,
};
export const SPECIAL_STRUCTURE_LIST = [
  STRUCTURECLASS.BRACELEFT,
  STRUCTURECLASS.BRACERIGHT,
];
export const TREE_TABLE_GROUP_LIST = [
  STRUCTURECLASS.TREETABLE,
  STRUCTURECLASS.TOPTITLETREETABLE,
];
export const MATRIX_GROUP_LIST = [
  STRUCTURECLASS.SPREADSHEET,
  STRUCTURECLASS.COLUMNSPREADSHEET,
];
export const TABLE_LIKE_STRUCTURE_LIST = [
  ...TREE_TABLE_GROUP_LIST,
  ...MATRIX_GROUP_LIST,
];
const BRACE_ENABLE_CONNECTION_LIST = [
  BRANCHCONNECTION.BRACE,
  BRANCHCONNECTION.BRACE2,
  BRANCHCONNECTION.BRACE3,
  BRANCHCONNECTION.BRACE4,
  BRANCHCONNECTION.BRACE5,
];
export const SPECIAL_STRUCTURE_TO_ENABLE_CONNECTION_LIST_MAP = {
  [STRUCTURECLASS.BRACELEFT]: BRACE_ENABLE_CONNECTION_LIST,
  [STRUCTURECLASS.BRACERIGHT]: BRACE_ENABLE_CONNECTION_LIST,
};
export const DEFAULT_STRUCTURE = STRUCTURECLASS.MAP;
export const TIMELINE_SIDED_STRUCTURES = [
  STRUCTURECLASS.TIMELINESIDEDHORIZONTAL,
];
