import { NodeStyle, ConnectionStyle } from './types/style'

export const DEFAULT_TOPIC_STYLE: NodeStyle = {
  shapeClass: 'roundedRect',
  cornerRadius: 8,
  fillColor: '#4A90D9',
  fillOpacity: 1,
  borderColor: '#2E6DB4',
  borderWidth: 2,
  borderStyle: 'solid',
  borderOpacity: 1,
  fontFamily: 'Arial',
  fontSize: 14,
  fontWeight: 'normal',
  fontStyle: 'normal',
  textColor: '#333',
  textAlign: 'center',
  textDecoration: 'none',
  textTransform: 'none',
  lineHeight: 1.2,
  paddingTop: 10,
  paddingRight: 20,
  paddingBottom: 10,
  paddingLeft: 20,
  marginTop: 5,
  marginRight: 10,
  marginBottom: 5,
  marginLeft: 10,
}

export const DEFAULT_CONNECTION_STYLE: ConnectionStyle = {
  lineClass: 'curve',
  lineColor: '#999',
  lineWidth: 2,
  lineStyle: 'solid',
  lineOpacity: 1,
  lineCorner: 8,
  tapered: false,
}

export const LAYOUT_CONSTANTS = {
  PADDING: 20,
  BOUNDARYGAP: 10,
  SUMMARYLINEMARGIN: {
    TOSUMMARY: 10,
    TORANGE: 10,
    TOBOUNDARY: 5,
  },
  LINECOLPOS: 13,
  STACKGAP: 5,
  COL_GAP: 13,
  EXT_GAP: 14,
  COL_RADIUS: 6,
  EXT_RADIUS: 8,
}

export const DEFAULT_KEYMAP: Record<string, string> = {
  'Tab': 'addSubTopic',
  'Enter': 'addSiblingTopic',
  'Shift+Enter': 'addTopicBefore',
  'Delete': 'deleteNode',
  'Backspace': 'deleteNode',
  'F2': 'startEditing',
  'Escape': 'cancelEditing',
  'Ctrl+a': 'selectAll',
  'Ctrl+z': 'undo',
  'Ctrl+Shift+z': 'redo',
  'Ctrl+c': 'copy',
  'Ctrl+x': 'cut',
  'Ctrl+v': 'paste',
  'Ctrl+=': 'zoomIn',
  'Ctrl+-': 'zoomOut',
  'Ctrl+0': 'resetZoom',
  'Ctrl+Shift+0': 'fitToContent',
  'ArrowUp': 'selectPrevious',
  'ArrowDown': 'selectNext',
  'ArrowLeft': 'selectParent',
  'ArrowRight': 'selectFirstChild',
  'Space': 'toggleFold',
}
