export const LIGHT_TEXT_COLOR = "#ffffff";
export const DARK_TEXT_COLOR = "#000000";
export const DEFAULT_COLOR_THEME_ID = "Rainbow-#000229-MULTI_LINE_COLORS";
export const DEAFULT_COLOR_THEME_FOR_SNOWBRUSH =
  "f079c1b6-809d-4e96-a846-bac157e0b71f";
export const DEFAULT_SKELETON_THEME_ID = "db4a5df4db39a8cd1310ea55ea";
export const SKELETON_GRAY_COLOR_THEME_ID =
  "902bcc3b-9ad2-42e9-84c6-f14c33dd55de";
export const CLASS_TYPE = {
  CENTRAL_TOPIC: "centralTopic",
  MAIN_TOPIC: "mainTopic",
  SUB_TOPIC: "subTopic",
  SUMMARY_TOPIC: "summaryTopic",
  CALLOUT_TOPIC: "calloutTopic",
  FLOATING_TOPIC: "floatingTopic",
  BOUNDARY: "boundary",
  SUMMARY: "summary",
  RELATIONSHIP: "relationship",
  MAP: "map",
  IMPORTANT_TOPIC: "importantTopic",
  MINOR_TOPIC: "minorTopic",
  EXPIRED_TOPIC: "expiredTopic",
  GLOBAL: "global",
};
export const LANGS = {
  ZH_CN: "zh-CN",
  EN_US: "en-US",
  ZH_HK: "zh-HK",
  ZH_TW: "zh-TW",
  JA_JP: "ja-JP",
  DE_DE: "de-DE",
  FR_FR: "fr-FR",
  ES_ES: "es",
  ID_ID: "id",
  IT_IT: "it-IT",
  KR_KR: "ko",
  PT_PT: "pt-PT",
  RU_RU: "ru-RU",
  TH_TH: "th",
};
export const COLOR_LIST_NAME = {
  LightGrayish: "LightGrayish",
  Light: "Light",
  LightPlus: "LightPlus",
  Dark: "Dark",
  Deep: "Deep",
  Pale: "Pale",
  PalePlus: "PalePlus",
  Dull: "Dull",
  V: "V",
  Bright: "Bright",
  S: "S",
  Soft: "Soft",
  GyLight: "GyLight",
  GyDark: "GyDark",
  Gray: "Gray",
  Grayish: "Grayish",
  MaterialPale: "MaterialPale",
  MaterialBright: "MaterialBright",
  MaterialBrightPlus: "MaterialBrightPlus",
  MaterialVivid: "MaterialVivid",
  MaterialVividPlus: "MaterialVividPlus",
  MaterialDeep: "MaterialDeep",
  MaterialDeepPlus: "MaterialDeepPlus",
  MaterialGray: "MaterialGray",
};
export const PRIMARY_COLOR_TYPE = {
  TYPE_A: "TYPE_A",
  TYPE_B: "TYPE_B",
  TYPE_C: "TYPE_C",
  MULTI_LINE_COLORS: "MULTI_LINE_COLORS",
};
export const SMART_COLOR_THEME_KEY_VALUE = {
  colorfulMinL: 20,
  colorfulMaxL: 80,
};
export const SMART_TEXT_FALLBACK_COLOR = {
  WHITE: "#ffffff",
  BLACK: "#101010",
};
export const SMART_COLOR_THEME_NAME = {
  Energy: "Energy",
  Freshness: "Freshness",
  Kimono: "Kimono",
  Forid: "Forid",
  Elegant: "Elegant",
  Quaint: "Quaint",
  Variety: "Variety",
  Dazzling: "Dazzling",
  Vintage: "Vintage",
  Dessert: "Dessert",
  Vanllia: "Vanllia",
  Candy: "Candy",
  Pebble: "Pebble",
  GreenTea: "GreenTea",
  CyberPunk: "CyberPunk",
  PurpleLight: "PurpleLight",
  Space: "Space",
  Sakura: "Sakura",
  Fire: "Fire",
  Christmas: "Christmas",
  Ink: "Ink",
  DeepSea: "DeepSea",
  Islands: "Islands",
  Latte: "Latte",
  Violet: "Violet",
  Roses: "Roses",
  Rainforest: "Rainforest",
  Rainbow: "Rainbow",
};
export const SMART_COLOR_THEME_NAME_ORDER = [
  SMART_COLOR_THEME_NAME.Rainbow,
  SMART_COLOR_THEME_NAME.Energy,
  SMART_COLOR_THEME_NAME.Freshness,
  SMART_COLOR_THEME_NAME.Kimono,
  SMART_COLOR_THEME_NAME.Forid,
  SMART_COLOR_THEME_NAME.Quaint,
  SMART_COLOR_THEME_NAME.Variety,
  SMART_COLOR_THEME_NAME.Dazzling,
  SMART_COLOR_THEME_NAME.Vintage,
  SMART_COLOR_THEME_NAME.Dessert,
  SMART_COLOR_THEME_NAME.Vanllia,
  SMART_COLOR_THEME_NAME.Candy,
  SMART_COLOR_THEME_NAME.GreenTea,
  SMART_COLOR_THEME_NAME.CyberPunk,
  SMART_COLOR_THEME_NAME.Space,
  SMART_COLOR_THEME_NAME.Sakura,
  SMART_COLOR_THEME_NAME.Fire,
  SMART_COLOR_THEME_NAME.Christmas,
  SMART_COLOR_THEME_NAME.DeepSea,
  SMART_COLOR_THEME_NAME.Islands,
  SMART_COLOR_THEME_NAME.Violet,
  SMART_COLOR_THEME_NAME.Roses,
  SMART_COLOR_THEME_NAME.Rainforest,
];
const RAINBOW_MAIN_COLOR_LIST = [
  "#000229",
  "#D9D34E",
  "#52CC83",
  "#4D86DB",
  "#99142F",
  "#245570",
];
export const RAINBOW_MULTI_COLOR_LIST = [
  ["#F9423A", "#F6A04D", "#F3D321", "#00BC7B", "#486AFF", "#4D49BE"],
  ["#ffa787", "#f19896", "#dec4ca", "#5bafc4", "#ffbe71", "#d98ea5"],
  ["#E7C2C0", "#F3D4B2", "#D8DCAF", "#A8D4CC", "#B0C0D0", "#C8BAC9"],
  ["#D3BD6C", "#ADB66B", "#76B18A", "#54A39B", "#5192A4", "#7878A0"],
  ["#F2D96E", "#FFBE71", "#FA8155", "#A61D39", "#C53F4D", "#FFA787"],
  ["#0B5D99", "#534E96", "#7B4083", "#A23E6A", "#C34150", "#CA5835"],
];
export const RAINBOW_QUICK_COLOR_LIST = [
  {
    [CLASS_TYPE.IMPORTANT_TOPIC]: "#A10000",
    [CLASS_TYPE.MINOR_TOPIC]: "#A37600",
  },
  {
    [CLASS_TYPE.IMPORTANT_TOPIC]: "#D24ED9",
    [CLASS_TYPE.MINOR_TOPIC]: "#4ED9D2",
  },
  {
    [CLASS_TYPE.IMPORTANT_TOPIC]: "#CC8352",
    [CLASS_TYPE.MINOR_TOPIC]: "#8352CC",
  },
  {
    [CLASS_TYPE.IMPORTANT_TOPIC]: "#86DB4D",
    [CLASS_TYPE.MINOR_TOPIC]: "#DB4D86",
  },
  {
    [CLASS_TYPE.IMPORTANT_TOPIC]: "#142F99",
    [CLASS_TYPE.MINOR_TOPIC]: "#2F9914",
  },
  {
    [CLASS_TYPE.IMPORTANT_TOPIC]: "#557024",
    [CLASS_TYPE.MINOR_TOPIC]: "#702455",
  },
];
export const SMART_COLOR_THEME_COLOR_LIST_MAP = {
  [SMART_COLOR_THEME_NAME.Energy]: [
    "#FFFFFF",
    "#F2F2F2",
    "#F22816",
    "#F2B807",
    "#233ED9",
    "#0D0D0D",
  ],
  [SMART_COLOR_THEME_NAME.Freshness]: [
    "#f0f0f0",
    "#F2BDC7",
    "#F2DC6B",
    "#5BA683",
    "#B796D9",
    "#3C74A6",
  ],
  [SMART_COLOR_THEME_NAME.Kimono]: [
    "#FFFFFF",
    "#FFABAA",
    "#FF7B31",
    "#8CB5FF",
    "#4A51D9",
    "#191959",
  ],
  [SMART_COLOR_THEME_NAME.Forid]: [
    "#EDF3FF",
    "#C1E554",
    "#FFAA39",
    "#D389D5",
    "#1692D2",
    "#0A052E",
  ],
  [SMART_COLOR_THEME_NAME.Elegant]: [
    "#FFFFF3",
    "#6C3EEE",
    "#6278F6",
    "#D94A6E",
    "#FFC762",
    "#2E1264",
  ],
  [SMART_COLOR_THEME_NAME.Quaint]: [
    "#F9F5DE",
    "#DFDDCE",
    "#4B9D9D",
    "#7884A4",
    "#AA79AA",
    "#153E5D",
  ],
  [SMART_COLOR_THEME_NAME.Variety]: [
    "#F6F5F5",
    "#9BFFED",
    "#FFC947",
    "#E46D57",
    "#1F3C88",
    "#070D59",
  ],
  [SMART_COLOR_THEME_NAME.Dazzling]: [
    "#FFFFFF",
    "#EFD7E6",
    "#FF7DC1",
    "#A239EA",
    "#5C37E5",
    "#092933",
  ],
  [SMART_COLOR_THEME_NAME.Vintage]: [
    "#E9C46A",
    "#F4A261",
    "#DC856F",
    "#2A9D8F",
    "#264653",
  ],
  [SMART_COLOR_THEME_NAME.Vanllia]: [
    "#FFFFFF",
    "#E4F9F5",
    "#30E3CA",
    "#11999E",
    "#40514E",
    "#0D4040",
  ],
  [SMART_COLOR_THEME_NAME.Pebble]: [
    "#25282F",
    "#7d9192",
    "#ffffff",
    "#b9b2ba",
    "#6a6778",
  ],
  [SMART_COLOR_THEME_NAME.GreenTea]: [
    "#D6D9C3",
    "#b6ad90",
    "#579360",
    "#656d4a",
    "#265834",
    "#1F2B1D",
  ],
  [SMART_COLOR_THEME_NAME.CyberPunk]: [
    "#ffffff",
    "#72efdd",
    "#56cfe1",
    "#4ea8de",
    "#5e60ce",
    "#7400b8",
  ],
  [SMART_COLOR_THEME_NAME.PurpleLight]: [
    "#9ba9ff",
    "#afb1ff",
    "#c4baff",
    "#d8c2ff",
    "#eccaff",
    "#FFFFFF",
  ],
  [SMART_COLOR_THEME_NAME.Fire]: [
    "#FDD29A",
    "#F9A655",
    "#FC901A",
    "#E04B51",
    "#A4564C",
    "#6D3B37",
  ],
  [SMART_COLOR_THEME_NAME.Ink]: [
    "#553343",
    "#E4D8D3",
    "#8A9E85",
    "#CAF8FD",
    "#C1C7F2",
    "#757CA3",
  ],
  [SMART_COLOR_THEME_NAME.DeepSea]: [
    "#B4F2FD",
    "#6EE2FD",
    "#3BB6E3",
    "#135CAE",
    "#01206A",
    "#000D2D",
  ],
  [SMART_COLOR_THEME_NAME.Islands]: [
    "#ffe8d6",
    "#ddbea9",
    "#cb997e",
    "#b7b7a4",
    "#a5a58d",
    "#6b705c",
  ],
  [SMART_COLOR_THEME_NAME.Latte]: [
    "#ffedd8",
    "#e7bc91",
    "#bc8a5f",
    "#8b5e34",
    "#6f4518",
    "#583101",
  ],
  [SMART_COLOR_THEME_NAME.Violet]: [
    "#FFFBEF",
    "#FBD58A",
    "#DCBEF4",
    "#b67be6",
    "#9d4edd",
    "#72369d",
  ],
  [SMART_COLOR_THEME_NAME.Roses]: [
    "#fff0f3",
    "#ffccd5",
    "#ffb3c1",
    "#ff758f",
    "#c9184a",
    "#a4133c",
  ],
  [SMART_COLOR_THEME_NAME.Rainforest]: [
    "#ffffff",
    "#c4fff9",
    "#9ceaef",
    "#68d8d6",
    "#06AFA9",
    "#046562",
  ],
  [SMART_COLOR_THEME_NAME.Vintage]: [
    "#E9C46A",
    "#F4A261",
    "#DC856F",
    "#A4705E",
    "#2A9D8F",
    "#264653",
  ],
  [SMART_COLOR_THEME_NAME.Dessert]: [
    "#F9F8ED",
    "#FFEDD2",
    "#FFBC9F",
    "#D8AC8F",
    "#83c5be",
    "#006d77",
  ],
  [SMART_COLOR_THEME_NAME.Candy]: [
    "#ffffff",
    "#FF9C72",
    "#f5cd6c",
    "#F09E3A",
    "#9cc3e4",
    "#54A6D6",
  ],
  [SMART_COLOR_THEME_NAME.Space]: [
    "#d9dcd6",
    "#81c3d7",
    "#3a7ca5",
    "#2f6690",
    "#16425b",
    "#0D2F42",
  ],
  [SMART_COLOR_THEME_NAME.Sakura]: [
    "#FFE3E8",
    "#FFDCC8",
    "#FFB4B6",
    "#FFA9C6",
    "#D1C3BD",
    "#C1CFDE",
  ],
  [SMART_COLOR_THEME_NAME.Christmas]: [
    "#D5F2E3",
    "#F0A346",
    "#E12A37",
    "#BC191E",
    "#2D6C65",
    "#101F23",
  ],
  [SMART_COLOR_THEME_NAME.Rainbow]: RAINBOW_MAIN_COLOR_LIST,
};

export const COLOR_THEME_NAME = {
  VLight: "Vivid Light",
  VDark: "Vivid Dark",
  VColorful: "Vivid Colorful",
  LightGrayish: "Light Grayish",
  LightDark: "Light Dark",
  LightColorful: "Light Colorful",
  Gray: "Gray",
  GrayLight: "Gray Light",
  GrayDark: "Gray Dark",
  Classic: "Classic",
  ClassicColorful: "Classic Colorful",
  Mono: "Mono",
  RainBow: "Rainbow",
  SkeletonGray: "SkeletonGray",
};
export const SKELETON_THEME_NAME = {
  MindMap: "Mind Map",
  BraceMap: "Brace Map",
  LogicChart: "Logic Chart",
  OrgChart: "Org Chart",
  TreeChart: "Tree Chart",
  Timeline: "Timeline",
  Fishbone: "Fishbone",
  TreeTable: "Tree Table",
  Matrix: "Matrix",
};
export const DEFAULT_SKELETON_THEME_ORDER = [
  SKELETON_THEME_NAME.MindMap,
  SKELETON_THEME_NAME.LogicChart,
  SKELETON_THEME_NAME.BraceMap,
  SKELETON_THEME_NAME.OrgChart,
  SKELETON_THEME_NAME.TreeChart,
  SKELETON_THEME_NAME.Timeline,
  SKELETON_THEME_NAME.Fishbone,
  SKELETON_THEME_NAME.TreeTable,
  SKELETON_THEME_NAME.Matrix,
];

export const DEFAULT_COLOR_THEME_ORDER = [
  COLOR_THEME_NAME.Classic,
  COLOR_THEME_NAME.ClassicColorful,
  COLOR_THEME_NAME.VLight,
  COLOR_THEME_NAME.VDark,
  COLOR_THEME_NAME.VColorful,
  COLOR_THEME_NAME.LightGrayish,
  COLOR_THEME_NAME.LightDark,
  COLOR_THEME_NAME.LightColorful,
  COLOR_THEME_NAME.Gray,
  COLOR_THEME_NAME.Mono,
  COLOR_THEME_NAME.RainBow,
];
export const PCCS_COLOR_MAP = {
  Happiness: {
    list: [
      "#b91f57",
      "#d02f48",
      "#dd443b",
      "#e95b23",
      "#e67800",
      "#f49d00",
      "#f1b500",
      "#eec900",
      "#d2c100",
      "#a8bb00",
      "#58a91d",
      "#00a15a",
      "#00926e",
      "#00857f",
      "#007488",
      "#00709b",
      "#00609c",
      "#005ba5",
      "#1a54a5",
      "#534aa0",
      "#703f96",
      "#81378a",
      "#8f2e7c",
      "#ad2e6c",
    ],
  },
  [COLOR_LIST_NAME.Bright]: {
    list: [
      "#ef6c70",
      "#fa8155",
      "#ffad36",
      "#fad831",
      "#b7c82b",
      "#41b879",
      "#00aa9f",
      "#0098b9",
      "#2981c0",
      "#7574bc",
      "#a165a8",
      "#d0678e",
    ],
  },
  [COLOR_LIST_NAME.Soft]: {
    list: [
      "#ca8281",
      "#da927a",
      "#dba66b",
      "#d3bd6c",
      "#adb66b",
      "#76b18a",
      "#54a39b",
      "#5192a4",
      "#5d7ea0",
      "#7878a0",
      "#907194",
      "#b4788b",
    ],
  },
  [COLOR_LIST_NAME.Deep]: {
    list: [
      "#a61d39",
      "#ab3d1d",
      "#b16c00",
      "#b39300",
      "#748400",
      "#007243",
      "#006664",
      "#005476",
      "#004280",
      "#3e337b",
      "#612469",
      "#861d55",
    ],
  },
  [COLOR_LIST_NAME.LightPlus]: {
    list: [
      "#f19896",
      "#ffa787",
      "#ffbe71",
      "#f2d96e",
      "#c7d36d",
      "#85ce9e",
      "#62c0b5",
      "#5bafc4",
      "#6c9ac5",
      "#9091c3",
      "#b088b5",
      "#d98ea5",
    ],
  },
  [COLOR_LIST_NAME.Light]: {
    list: [
      "#f6aba5",
      "#ffb99e",
      "#ffce90",
      "#fbe68f",
      "#d8df92",
      "#9cd9ac",
      "#7eccc1",
      "#79baca",
      "#83a7c8",
      "#a29fc7",
      "#b89ab8",
      "#daa0b3",
    ],
  },
  [COLOR_LIST_NAME.Dull]: {
    list: [
      "#a35a5c",
      "#af6954",
      "#b37f46",
      "#ab9446",
      "#858f46",
      "#4f8766",
      "#2a7b76",
      "#246a7d",
      "#34597d",
      "#54527c",
      "#6c4a71",
      "#8b4f65",
    ],
  },
  [COLOR_LIST_NAME.Dark]: {
    list: [
      "#692934",
      "#75362a",
      "#794d1c",
      "#74601f",
      "#525b20",
      "#23523a",
      "#004746",
      "#004558",
      "#123452",
      "#322d51",
      "#432848",
      "#612d46",
    ],
  },
  [COLOR_LIST_NAME.PalePlus]: {
    list: [
      "#e8c2bf",
      "#ebc2b5",
      "#f4d4b0",
      "#f2e6b8",
      "#d8ddad",
      "#aed4b9",
      "#a6d4cc",
      "#add1da",
      "#afc0d1",
      "#bbbdd0",
      "#c8b9c9",
      "#dec4ca",
    ],
  },
  [COLOR_LIST_NAME.Pale]: {
    list: [
      "#e7d5d4",
      "#e9d5cf",
      "#f6e3ce",
      "#efe6c6",
      "#e6e9c6",
      "#c4e0cb",
      "#bfe0d9",
      "#c6dde2",
      "#c2ccd5",
      "#c9cad5",
      "#d0c8d1",
      "#e4d5d9",
    ],
  },
  [COLOR_LIST_NAME.LightGrayish]: {
    list: [
      "#c0abaa",
      "#c1aba5",
      "#cebba8",
      "#c6bea1",
      "#bdc1a2",
      "#9db6a5",
      "#98b6b1",
      "#9eb4b9",
      "#9ba5af",
      "#a2a2af",
      "#aba0ab",
      "#bdacb0",
    ],
  },
  [COLOR_LIST_NAME.Grayish]: {
    list: [
      "#745c5c",
      "#755c57",
      "#806c5c",
      "#786f57",
      "#6e725a",
      "#53665a",
      "#4e6764",
      "#4f656c",
      "#4c5765",
      "#565566",
      "#605262",
      "#725c63",
    ],
  },
  DarkGrayish: {
    list: [
      "#3e2d30",
      "#3f2e2c",
      "#4a3c32",
      "#443e30",
      "#3d4033",
      "#2a342e",
      "#273434",
      "#273439",
      "#222933",
      "#292734",
      "#302531",
      "#3d2e34",
    ],
  },
  [COLOR_LIST_NAME.Gray]: {
    list: [
      "#f1f1f1",
      "#d6d6d6",
      "#bbbbbb",
      "#a1a1a1",
      "#878787",
      "#6d6d6d",
      "#545454",
      "#3c3c3c",
      "#272727",
    ],
  },
  [COLOR_LIST_NAME.GyLight]: {
    list: ["#d6d6d6", "#bbbbbb", "#a1a1a1"],
  },
  [COLOR_LIST_NAME.GyDark]: {
    list: ["#6d6d6d", "#545454", "#3c3c3c"],
  },
  [COLOR_LIST_NAME.S]: {
    list: [
      "#c53f4d",
      "#cc572e",
      "#e19215",
      "#debc03",
      "#9cad00",
      "#008f56",
      "#00827c",
      "#006f92",
      "#005b9b",
      "#534c98",
      "#7c3d84",
      "#a33c6a",
    ],
  },
  [COLOR_LIST_NAME.V]: {
    list: [
      "#d02f48",
      "#e95b23",
      "#f49d00",
      "#eec900",
      "#a8bb00",
      "#00a15a",
      "#00857f",
      "#00709b",
      "#005ba5",
      "#534aa0",
      "#81378a",
      "#ad2e6c",
    ],
  },
  [COLOR_LIST_NAME.MaterialPale]: {
    list: [
      "#ffebee",
      "#FFF3E0",
      "#F9FBE7",
      "#E8F5E9",
      "#E0F2F1",
      "#E0F7FA",
      "#E3F2FD",
      "#E8EAF6",
      "#F3E5F5",
      "#FCE4EC",
    ],
  },
  [COLOR_LIST_NAME.MaterialBright]: {
    list: [
      "#ef5350",
      "#FFA726",
      "#D4E157",
      "#66BB6A",
      "#26A69A",
      "#26C6DA",
      "#42A5F5",
      "#5C6BC0",
      "#AB47BC",
      "#EC407A",
    ],
  },
  [COLOR_LIST_NAME.MaterialBrightPlus]: {
    list: [
      "#f44336",
      "#FF9800",
      "#CDDC39",
      "#4CAF50",
      "#009688",
      "#00BCD4",
      "#2196F3",
      "#3F51B5",
      "#9C27B0",
      "#E91E63",
    ],
  },
  [COLOR_LIST_NAME.MaterialVivid]: {
    list: [
      "#e53935",
      "#FB8C00",
      "#C0CA33",
      "#43A047",
      "#00897B",
      "#00ACC1",
      "#1E88E5",
      "#3949AB",
      "#8E24AA",
      "#D81B60",
    ],
  },
  [COLOR_LIST_NAME.MaterialVividPlus]: {
    list: [
      "#d32f2f",
      "#F57C00",
      "#AFB42B",
      "#388E3C",
      "#00796B",
      "#0097A7",
      "#1976D2",
      "#303F9F",
      "#7B1FA2",
      "#C2185B",
    ],
  },
  [COLOR_LIST_NAME.MaterialDeep]: {
    list: [
      "#c62828",
      "#EF6C00",
      "#9E9D24",
      "#2E7D32",
      "#00695C",
      "#00838F",
      "#1565C0",
      "#283593",
      "#6A1B9A",
      "#AD1457",
    ],
  },
  [COLOR_LIST_NAME.MaterialDeepPlus]: {
    list: [
      "#b71c1c",
      "#E65100",
      "#827717",
      "#1B5E20",
      "#004D40",
      "#006064",
      "#0D47A1",
      "#1A237E",
      "#4A148C",
      "#880E4F",
    ],
  },
  [COLOR_LIST_NAME.MaterialGray]: {
    list: [
      "#FAFAFA",
      "#F5F5F5",
      "#EEEEEE",
      "#E0E0E0",
      "#BDBDBD",
      "#9E9E9E",
      "#757575",
      "#616161",
      "#424242",
      "#212121",
    ],
  },
};
export const STYLE_KEYS = {
  FONT_FAMILY: "fo:font-family",
  FONT_STYLE: "fo:font-style",
  FONT_WEIGHT: "fo:font-weight",
  FONT_SIZE: "fo:font-size",
  TEXT_COLOR: "fo:color",
  TEXT_ALIGN: "fo:text-align",
  TEXT_BULLET: "fo:text-bullet",
  TEXT_TRANSFORM: "fo:text-transform",
  TEXT_DECORATION: "fo:text-decoration",
  TEXT_BACKGROUND_COLOR: "fo:background-color",
  MARGIN_LEFT: "fo:margin-left",
  MARGIN_RIGHT: "fo:margin-right",
  MARGIN_TOP: "fo:margin-top",
  MARGIN_BOTTOM: "fo:margin-bottom",
  SPACING_MAJOR: "spacing-major",
  SPACING_MINOR: "spacing-minor",
  SHAPE_CLASS: "shape-class",
  SHAPE_CORNER: "shape-corner",
  LINE_CORNER: "line-corner",
  LINE_COLOR: "line-color",
  LINE_CLASS: "line-class",
  LINE_WIDTH: "line-width",
  LINE_PATTERN: "line-pattern",
  LINE_TAPERED: "line-tapered",
  BORDER_LINE_COLOR: "border-line-color",
  BORDER_LINE_WIDTH: "border-line-width",
  BORDER_LINE_PATTERN: "border-line-pattern",
  CALLOUT_FILL_COLOR: "callout-fill-color",
  CALLOUT_LINE_CLASS: "callout-line-class",
  CALLOUT_LINE_CORNER: "callout-line-corner",
  CALLOUT_LINE_PATTERN: "callout-line-pattern",
  CALLOUT_LINE_WIDTH: "callout-line-width",
  CALLOUT_SHAPE_CLASS: "callout-shape-class",
  CALLOUT_LINE_COLOR: "callout-line-color",
  OPACITY: "svg:opacity",
  FILL_COLOR: "svg:fill",
  BACKGROUND: "background",
  ARROW_END_CLASS: "arrow-end-class",
  ARROW_BEGIN_CLASS: "arrow-begin-class",
  ALLOW_OVERLAP: "allow-overlap",
  ALLOW_FREE_POSITION: "allow-free-position",
  GRADIENT_COLOR: "color-gradient",
  MULTI_LINE_COLORS: "multi-line-colors",
  CJK_FONT_FAMILY: "cjk-font-family",
  STRUCTURE_CLASS: "structure-class",
  COLOR_LIST: "color-list",
  FILL_GRADIENT: "fill-gradient",
  BORDER_GRADIENT: "border-gradient",
  ALIGNMENT_BY_LEVEL: "alignment-by-level",
  FILL_PATTERN: "fill-pattern",
};
export const TOPIC_SKELETON_STYLE_KEY_LIST = [
  STYLE_KEYS.SHAPE_CLASS,
  STYLE_KEYS.BORDER_LINE_WIDTH,
  STYLE_KEYS.LINE_CLASS,
  STYLE_KEYS.LINE_WIDTH,
  STYLE_KEYS.FILL_COLOR,
  STYLE_KEYS.BORDER_LINE_COLOR,
  STYLE_KEYS.FONT_FAMILY,
  STYLE_KEYS.FONT_STYLE,
  STYLE_KEYS.FONT_WEIGHT,
  STYLE_KEYS.FONT_SIZE,
  STYLE_KEYS.TEXT_TRANSFORM,
  STYLE_KEYS.TEXT_DECORATION,
  STYLE_KEYS.LINE_PATTERN,
  STYLE_KEYS.FILL_PATTERN,
  STYLE_KEYS.BORDER_LINE_PATTERN,
  STYLE_KEYS.ARROW_END_CLASS,
];

export const TOPIC_COLOR_STYLE_KEY_LIST = [
  STYLE_KEYS.FILL_COLOR,
  STYLE_KEYS.BORDER_LINE_COLOR,
  STYLE_KEYS.LINE_COLOR,
  STYLE_KEYS.TEXT_COLOR,
];
export const COLOR_FIELDS = {
  PRIMARY_COLOR_0: "PRIMARY_COLOR_0",
  PRIMARY_COLOR_1: "PRIMARY_COLOR_1",
  PRIMARY_COLOR_2: "PRIMARY_COLOR_2",
  PRIMARY_COLOR_3: "PRIMARY_COLOR_3",
  PRIMARY_COLOR_4: "PRIMARY_COLOR_4",
  SECONDARY_COLOR_1: "SECONDARY_COLOR_1",
  SECONDARY_COLOR_2: "SECONDARY_COLOR_2",
  SECONDARY_COLOR_3: "SECONDARY_COLOR_3",
  QUICK_COLOR_1: "QUICK_COLOR_1",
  QUICK_COLOR_2: "QUICK_COLOR_2",
  QUICK_COLOR_3: "QUICK_COLOR_3",
  LIGHT_COLOR: "LIGHT_COLOR",
  DARK_COLOR: "DARK_COLOR",
  TRANSPARENT: "TRANSPARENT",
  MULTI_LINE_COLORS: "MULTI_LINE_COLORS",
  COLOR_LIST: "COLOR_LIST",
};
export const TOPIC_CLASS_TYPE_LIST = [
  CLASS_TYPE.CENTRAL_TOPIC,
  CLASS_TYPE.MAIN_TOPIC,
  CLASS_TYPE.SUB_TOPIC,
  CLASS_TYPE.FLOATING_TOPIC,
  CLASS_TYPE.SUMMARY_TOPIC,
  CLASS_TYPE.CALLOUT_TOPIC,
  CLASS_TYPE.IMPORTANT_TOPIC,
  CLASS_TYPE.MINOR_TOPIC,
];
export const QUICK_TOPIC_CLASS_TYPE_LIST = [
  CLASS_TYPE.IMPORTANT_TOPIC,
  CLASS_TYPE.MINOR_TOPIC,
  CLASS_TYPE.EXPIRED_TOPIC,
];
export const PRESET_GLOBAL_STYLE_CLASS = CLASS_TYPE.GLOBAL;
export const COLOR_THEME_PREVIEW_TYPE = {
  MAP: "MAP",
  TABLE: "TABLE",
};
export const STYLE_KEY_TO_PREVIEW_PARAM_KEY = {
  [STYLE_KEYS.TEXT_COLOR]: "textColor",
  [STYLE_KEYS.FILL_COLOR]: "fillColor",
  [STYLE_KEYS.LINE_COLOR]: "lineColor",
  [STYLE_KEYS.BORDER_LINE_COLOR]: "borderLineColor",
};
function getRainbowColorList(indexInfoList) {
  return indexInfoList.map((info) => {
    return PCCS_COLOR_MAP[info.colorListName].list[info.index / 2 - 1];
  });
}
export const RAINBOW_LIGHT_COLOR_LIST = [
  getRainbowColorList([
    {
      colorListName: COLOR_LIST_NAME.Bright,
      index: 4,
    },
    {
      colorListName: COLOR_LIST_NAME.Bright,
      index: 6,
    },
    {
      colorListName: COLOR_LIST_NAME.Bright,
      index: 10,
    },
    {
      colorListName: COLOR_LIST_NAME.Bright,
      index: 16,
    },
    {
      colorListName: COLOR_LIST_NAME.Bright,
      index: 20,
    },
    {
      colorListName: COLOR_LIST_NAME.Bright,
      index: 22,
    },
  ]),
  getRainbowColorList([
    {
      colorListName: COLOR_LIST_NAME.LightPlus,
      index: 8,
    },
    {
      colorListName: COLOR_LIST_NAME.LightPlus,
      index: 6,
    },
    {
      colorListName: COLOR_LIST_NAME.Bright,
      index: 4,
    },
    {
      colorListName: COLOR_LIST_NAME.Deep,
      index: 2,
    },
    {
      colorListName: COLOR_LIST_NAME.S,
      index: 2,
    },
    {
      colorListName: COLOR_LIST_NAME.LightPlus,
      index: 4,
    },
  ]),
  getRainbowColorList([
    {
      colorListName: COLOR_LIST_NAME.MaterialBrightPlus,
      index: 14,
    },
    {
      colorListName: COLOR_LIST_NAME.MaterialVivid,
      index: 14,
    },
    {
      colorListName: COLOR_LIST_NAME.MaterialVividPlus,
      index: 14,
    },
    {
      colorListName: COLOR_LIST_NAME.MaterialDeep,
      index: 14,
    },
    {
      colorListName: COLOR_LIST_NAME.MaterialDeepPlus,
      index: 14,
    },
    {
      colorListName: COLOR_LIST_NAME.MaterialDeep,
      index: 16,
    },
  ]),
  getRainbowColorList([
    {
      colorListName: COLOR_LIST_NAME.PalePlus,
      index: 2,
    },
    {
      colorListName: COLOR_LIST_NAME.PalePlus,
      index: 6,
    },
    {
      colorListName: COLOR_LIST_NAME.PalePlus,
      index: 10,
    },
    {
      colorListName: COLOR_LIST_NAME.PalePlus,
      index: 14,
    },
    {
      colorListName: COLOR_LIST_NAME.PalePlus,
      index: 18,
    },
    {
      colorListName: COLOR_LIST_NAME.PalePlus,
      index: 22,
    },
  ]),
  getRainbowColorList([
    {
      colorListName: COLOR_LIST_NAME.Grayish,
      index: 2,
    },
    {
      colorListName: COLOR_LIST_NAME.LightGrayish,
      index: 6,
    },
    {
      colorListName: COLOR_LIST_NAME.LightGrayish,
      index: 12,
    },
    {
      colorListName: COLOR_LIST_NAME.Grayish,
      index: 18,
    },
    {
      colorListName: COLOR_LIST_NAME.Soft,
      index: 12,
    },
    {
      colorListName: COLOR_LIST_NAME.Soft,
      index: 4,
    },
  ]),
  getRainbowColorList([
    {
      colorListName: COLOR_LIST_NAME.S,
      index: 18,
    },
    {
      colorListName: COLOR_LIST_NAME.S,
      index: 20,
    },
    {
      colorListName: COLOR_LIST_NAME.S,
      index: 22,
    },
    {
      colorListName: COLOR_LIST_NAME.S,
      index: 24,
    },
    {
      colorListName: COLOR_LIST_NAME.S,
      index: 2,
    },
    {
      colorListName: COLOR_LIST_NAME.S,
      index: 4,
    },
  ]),
  getRainbowColorList([
    {
      colorListName: COLOR_LIST_NAME.LightPlus,
      index: 4,
    },
    {
      colorListName: COLOR_LIST_NAME.LightPlus,
      index: 2,
    },
    {
      colorListName: COLOR_LIST_NAME.PalePlus,
      index: 24,
    },
    {
      colorListName: COLOR_LIST_NAME.LightPlus,
      index: 16,
    },
    {
      colorListName: COLOR_LIST_NAME.LightPlus,
      index: 6,
    },
    {
      colorListName: COLOR_LIST_NAME.LightPlus,
      index: 24,
    },
  ]),
  getRainbowColorList([
    {
      colorListName: COLOR_LIST_NAME.Soft,
      index: 6,
    },
    {
      colorListName: COLOR_LIST_NAME.Soft,
      index: 10,
    },
    {
      colorListName: COLOR_LIST_NAME.Soft,
      index: 12,
    },
    {
      colorListName: COLOR_LIST_NAME.Soft,
      index: 14,
    },
    {
      colorListName: COLOR_LIST_NAME.Soft,
      index: 16,
    },
    {
      colorListName: COLOR_LIST_NAME.Soft,
      index: 20,
    },
  ]),
];
export const RAINBOW_MAP_FILL_COLOR_L = {
  LIGHT_MIN_L: 90,
  DARK_MAX_L: 25,
};
export const COLOR_MIN_RATIO = 1.3;
export const TEXT_MIN_RATIO = 3;
const HAND_DRAWN_FILL_PATTERN = {
  SOLID_HAND_DRAWN: "solid-hand-drawn",
  HACHURE: "hachure",
  HACHURE_LEFT_HAND: "hachure-left-hand",
  ZIGZAG: "zigzag",
  ZIGZAG_LEFT_HAND: "zigzag-left-hand",
  CROSSING: "crossing", // 平行线, 方向水平
};
export const FILL_PATTERN = {
  NONE: "none",
  SOLID: "solid",
  ...HAND_DRAWN_FILL_PATTERN,
};
